DROP TABLE IF EXISTS Users;
DROP TABLE IF EXISTS Watch;
DROP TABLE IF EXISTS Movies;
DROP TABLE IF EXISTS Sources;
DROP TABLE IF EXISTS Uploads;

CREATE TABLE Users (
ID INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
Name VARCHAR(225) NOT NULL UNIQUE,
Genre VARCHAR(255) NOT NULL,
Profile VARCHAR(285) NOT NULL,
Type VARCHAR(200) NOT NULL);

CREATE TABLE Watch (
ID INT NOT NULL,
Title VARCHAR(255) NOT NULL,
UserID INT NOT NULL,
Hour INT NOT NULL,
Status BOOLEAN NOT NULL);

CREATE TABLE Movies (
ID INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
Title VARCHAR(255) NOT NULL UNIQUE,
Detail LONGTEXT NOT NULL,
Year YEAR NOT NULL,
Resolution INT NOT NULL,
Genre VARCHAR(255) NOT NULL,
Duration INT NOT NULL);

CREATE TABLE Sources (
ID INT NOT NULL,
Poster VARCHAR(255) NOT NULL,
Screenshot VARCHAR(255) NOT NULL,
Video VARCHAR(255) NOT NULL);

CREATE TABLE Uploads (
ID INT NOT NULL,
Year YEAR NOT NULL,
Data DATE NOT NULL,
Time TIME NOT NULL);

ALTER TABLE Watch ADD CONSTRAINT Watch_ID_Movies_ID FOREIGN KEY (ID) REFERENCES Movies(ID);
ALTER TABLE Watch ADD CONSTRAINT Watch_UserID_Users_ID FOREIGN KEY (UserID) REFERENCES Users(ID);
ALTER TABLE Sources ADD CONSTRAINT Sources_ID_Movies_ID FOREIGN KEY (ID) REFERENCES Movies(ID);
ALTER TABLE Uploads ADD CONSTRAINT Uploads_ID_Movies_ID FOREIGN KEY (ID) REFERENCES Movies(ID);
